### ISSUE TITLE
Missing (-8) timezone from dropdown

### ISSUE THREAD

**Issue by frankiewarren** [rgarcia/scheduleforlater.com#4]
Missing the important one! 

![screenshot 2015-04-08 22 34 56](https://cloud.githubusercontent.com/assets/1038425/7061102/ad7c8360-de41-11e4-8adb-74f1c8fd9ff2.png)

**Comment by rgarcia** [comment]
:facepalm: nice catch

**Comment by rgarcia** [comment]
fixed by #6
